import type { Plugin } from 'vite'

/**
 * PWA wiring for a GitHub-Pages-hosted Vite SPA.
 *
 * Why a hand-rolled plugin instead of vite-plugin-pwa / Workbox:
 *  - zero new runtime or dev dependencies (the project is deliberately lean),
 *  - the ONE thing that's actually hard here is the base path. This app serves
 *    at '/' locally and over Tailscale, but at '/hobbyist/' on GitHub Pages
 *    (VITE_BASE). The manifest's `start_url`/`scope`/icon `src` and the service
 *    worker's cache paths must all carry that same base, or "Add to Home
 *    Screen" installs a shortcut that 404s. We read `config.base` once and
 *    thread it through everything.
 *
 * What it does:
 *  - injects the manifest <link>, theme-color, and iOS standalone meta tags
 *    into index.html (base-correct) via transformIndexHtml,
 *  - emits manifest.webmanifest and sw.js as build assets (base-correct).
 *
 * The service worker is intentionally minimal: a cache-first "app shell" cache
 * so the app opens offline (the badge collection lives in localStorage, so an
 * offline open is genuinely useful — you can view your sash with no signal).
 * It is network-first for navigations so a fresh deploy is picked up, falling
 * back to the cached shell when offline.
 */
export function pwa(): Plugin {
  let base = '/'

  const theme = '#b45309' // copper — matches the badge ladder's base tier
  const bg = '#f8f9fa' // --bg from index.css

  const manifest = () =>
    JSON.stringify(
      {
        name: 'The Hobbyist',
        short_name: 'Hobbyist',
        description: 'Your hobby collection — one place to see yourself.',
        start_url: base,
        scope: base,
        display: 'standalone',
        orientation: 'portrait',
        background_color: bg,
        theme_color: theme,
        icons: [
          { src: `${base}icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
          { src: `${base}icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
          {
            src: `${base}icons/icon-512-maskable.png`,
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      null,
      2,
    )

  // Bump CACHE on any shell change so clients drop the stale cache.
  const sw = () => `// Auto-generated by scripts/pwa-plugin.ts — do not edit by hand.
const CACHE = 'hobbyist-shell-v1'
const BASE = ${JSON.stringify(base)}
const SHELL = [BASE, BASE + 'index.html']

self.addEventListener('install', (e) => {
  self.skipWaiting()
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL).catch(() => {})))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ),
  )
  self.clients.claim()
})

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return

  // Navigations: network-first (pick up new deploys), fall back to cached shell.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put(req, copy))
          return res
        })
        .catch(() => caches.match(req).then((m) => m || caches.match(BASE + 'index.html'))),
    )
    return
  }

  // Static assets: cache-first (hashed filenames make this safe).
  e.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        }),
    ),
  )
})
`

  return {
    name: 'hobbyist-pwa',
    configResolved(config) {
      base = config.base || '/'
    },
    transformIndexHtml() {
      return [
        { tag: 'link', attrs: { rel: 'manifest', href: `${base}manifest.webmanifest` }, injectTo: 'head' },
        { tag: 'meta', attrs: { name: 'theme-color', content: theme }, injectTo: 'head' },
        { tag: 'meta', attrs: { name: 'mobile-web-app-capable', content: 'yes' }, injectTo: 'head' },
        { tag: 'meta', attrs: { name: 'apple-mobile-web-app-capable', content: 'yes' }, injectTo: 'head' },
        {
          tag: 'meta',
          attrs: { name: 'apple-mobile-web-app-status-bar-style', content: 'default' },
          injectTo: 'head',
        },
        { tag: 'meta', attrs: { name: 'apple-mobile-web-app-title', content: 'Hobbyist' }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'apple-touch-icon', href: `${base}icons/apple-touch-icon.png` }, injectTo: 'head' },
      ]
    },
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: manifest() })
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw() })
    },
  }
}
